version: '3'

services:
  postgres:
    image: ${IMAGE_POSTGRES}
    hostname: ${CONTAINER_HOSTNAME}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    restart: unless-stopped
    networks:
      - pg-network

  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - pg-network

volumes:
  postgres-data:

networks: 
  pg-network:
    driver: bridge
