version: "3.7"

services:
  redis:
    image: ${IMAGE_REDIS}
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: ${REDIS_HOSTS}
      HTTP_USER: ${HTTP_USER}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  redis-data: